### ISSUE TITLE
只能聊天5次

### ISSUE THREAD

**Issue by AlanceLau** [jianjianai/microsoft-copilot-porxy#17]
只能进行5次对话

**Comment by jianjianai** [comment]
登录账号后对话30次，不登录使用edge浏览器对话10次。不使用edge浏览器也不登录只能对话5次。

**Comment by AlanceLau** [comment]
> 登录账号后对话30次，不登录使用edge浏览器对话10次。不使用edge浏览器也不登录只能对话5次。

登录了，也只有5次啊

**Comment by J-York** [comment]
> 登录账号后对话30次，不登录使用edge浏览器对话10次。不使用edge浏览器也不登录只能对话5次。

我这边也遇到了相同的问题，登录账号之后也只能进行五次对话，之后对话会被终止

**Comment by AlanceLau** [comment]
> > 登录账号后对话30次，不登录使用edge浏览器对话10次。不使用edge浏览器也不登录只能对话5次。
> 
> 我这边也遇到了相同的问题，登录账号之后也只能进行五次对话，之后对话会被终止

电脑edge浏览器确实就不是五次了，必须edge浏览器

**Comment by AlanceLau** [comment]
谢谢

**Comment by suows** [comment]
欸我以及登录了账号并且是edge浏览器，前几天还是30条限制，现在copilot只能对话五次，请问这个情况怎么回事呀？
