### ISSUE TITLE
画图的时候报错

### ISSUE THREAD

**Issue by renqabs** [jianjianai/microsoft-copilot-porxy#2]
![image](https://github.com/jianjianai/microsoft-copilot-porxy/assets/130155002/f163fdab-4345-49d0-a784-945544a8f2f7)
可以出图，但是会提示错误，不能继续对话。

**Comment by jianjianai** [comment]
画图完成之后会提交一个更新聊天记录的请求，用于保存画图的信息，但是这个请求非常玄学，有时候可以提交成功有时候会失败，失败的情况下就会出现这个问题。

等几天有空研究下这个问题。

**Comment by renqabs** [comment]
> 画图完成之后会提交一个更新聊天记录的请求，用于保存画图的信息，但是这个请求非常玄学，有时候可以提交成功有时候会失败，失败的情况下就会出现这个问题。
> 
> 等几天有空研究下这个问题。

好的，感谢大佬

**Comment by jianjianai** [comment]
已经修复这个问题了🎉
