### ISSUE TITLE
被cf认为是钓鱼攻击

### ISSUE THREAD

**Issue by AlanceLau** [jianjianai/microsoft-copilot-porxy#20]
This attack targets our customer, Microsoft, website URL https://www.microsoft.com/.

Would it be possible to have the fraudulent content, and any other associated fraudulent content, taken down as soon as you are able to?

Additionally, please keep the fraudulent content safe so that our customer and law enforcement agencies can investigate this incident further once the site is offline.

More information about the detected issue is provided at https://incident.netcraft.com/30fdda2c3528/

Many thanks,

**Comment by smaa** [comment]
我也收到了cf 发的邮件。这个像是Netcraft扫描到了站点

**Comment by AlanceLau** [comment]
> 我也收到了cf 发的邮件。这个像是Netcraft扫描到了站点

有点担心，已经关闭了

**Comment by jianjianai** [comment]
我也收到了,貌似没啥事。

**Comment by AlanceLau** [comment]
> 我也收到了,貌似没啥事。

那我就放心了，接着用

**Comment by b1ghawk119** [comment]
> > 我也收到了,貌似没啥事。
> 
> 那我就放心了，接着用

目前不仅仅是收到邮件，还会禁止访问目标站点。
