### ISSUE TITLE
演示站登陆账号出现问题

### ISSUE THREAD

**Issue by ningguoxu** [jianjianai/microsoft-copilot-porxy#21]
![Screenshot_2024-06-24-18-23-34-85_32cba261fc08a501ce70de75bdbe2575](https://github.com/jianjianai/microsoft-copilot-porxy/assets/87106666/3abcb814-27ee-4af3-863d-4fe5447aedd5)
登录不上

**Comment by jianjianai** [comment]
是用的什么方式登录的呢？

**Comment by ningguoxu** [comment]
反代网页内登录

**Comment by jianjianai** [comment]
啊这....,登录过程是什么呢？邮箱登录还是密码登录？中间有其他步骤吗？

**Comment by ningguoxu** [comment]
密码登录，没有过程，电脑端正常，手机端就不行

**Comment by ningguoxu** [comment]
![recording](https://github.com/jianjianai/microsoft-copilot-porxy/assets/87106666/a3f27587-5c74-40c1-989a-b93bf9a43608)
密码登录

**Comment by AlanceLau** [comment]
登录之后，总是提示人机验证

**Comment by jianjianai** [comment]
右上角，点个人账号登录会有这个问题吗？

**Comment by ningguoxu** [comment]
有，有这个问题。但是在Edge浏览器正常。

**Comment by ningguoxu** [comment]
> 登录之后，总是提示人机验证

添加变量 BYPASS_SERVER=https://bypass.b1ng.chat

**Comment by jianjianai** [comment]
神奇了，我3个账号都没触发这个问题。

**Comment by leioukupo** [comment]
> ![Screenshot_2024-06-24-18-23-34-85_32cba261fc08a501ce70de75bdbe2575](https://private-user-images.githubusercontent.com/87106666/342302417-3abcb814-27ee-4af3-863d-4fe5447aedd5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTIxMjcsIm5iZiI6MTcxOTgxMTgyNywicGF0aCI6Ii84NzEwNjY2Ni8zNDIzMDI0MTctM2FiY2I4MTQtMjdlZS00YWYzLTg2M2QtNGZlNTQ0N2FlZGQ1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA1MzAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzM2MwMzE4NjhhMDA4NTFiYjQ1M2M1ZWNjMzg2Njk1NGE2MTNlNzg5MDNhZWRiNmZhMGEwNzhlZmM0ZDBiZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cWuZeGl6JHk3ht7GyqwMiu8IlXYTUsjirw6ysPkM9cs) 登录不上

这已经登录了，你再重新进入就行了

**Comment by Mokenfly** [comment]
出现same hostname的原因貌似是因为是在登录的时候微软显示了这个界面，然后这个界面主机名是一样的，于是返回了same hostname
![9A1D9BEC-E220-4C48-8B2B-2BB969EDB861~2.png](https://github.com/user-attachments/assets/bec9fa3d-b077-4123-8c24-470f53ccd302)

**Comment by Mokenfly** [comment]
> 出现same hostname的原因貌似是因为是在登录的时候微软显示了这个界面，然后这个界面主机名是一样的，于是返回了same hostname
> ![9A1D9BEC-E220-4C48-8B2B-2BB969EDB861~2.png](https://github.com/user-attachments/assets/bec9fa3d-b077-4123-8c24-470f53ccd302)
> 
> 

解决这个问题最简单粗暴的办法是在 https://github.com/Mokenfly/ms-copilot-play/blob/master/src%2Fproxy%2FproxyLinkHttp.ts 文件里把这几行批注，然后即可登录
        // if (reqConfig.url.hostname == new URL(req.url).hostname) {
            // return new Response("Same hostname", { status: 404 });
        // }

**Comment by jianjianai** [comment]
已解决
