### ISSUE TITLE
部署到cloudflare后收到cloudflare的警告邮件

### ISSUE THREAD

**Issue by zc360** [jianjianai/microsoft-copilot-porxy#26]
# 以下是cloudflare发我的邮件内容

您好，

Cloudflare 收到了一份关于以下区域的 phishing report：口口口口口口口口.dev（部署的页面链接）

我们收到的信息如下：

报告者：匿名

报告 URL：

https://口口口口口口口口口口口口口口口口口口口口口口口口口口口口（部署的页面链接后加上一大堆）

滥用日志或证据：Hello,

We have discovered a phishing attack located on your network:

口口口口口口口口口口口口口口口口口口口口口口口口口口口口口口口口口口口口口口口口（部署的页面链接后加上一大堆）
This attack targets our customer, Microsoft, website URL https://www.microsoft.com/.

Would it be possible to have the fraudulent content, and any other associated fraudulent content, taken down as soon as you are able to?

Additionally, please keep the fraudulent content safe so that our customer and law enforcement agencies can investigate this incident further once the site is offline.

Many thanks,

Netcraft

Phone: +44(0)1225 447500
Fax: +44(0)1225 448600
Netcraft Issue Number: 59048038

注释：

我们已将此投诉转发给您的托管提供商。
谢谢，
Cloudflare 团队

**Comment by zc360** [comment]
![屏幕截图 2024-07-28 064019](https://github.com/user-attachments/assets/4a451d22-a191-460e-b9f5-7831e048e1e2)
再次访问还会有警告

**Comment by zc360** [comment]
![屏幕截图 2024-07-28 064019](https://github.com/user-attachments/assets/ee535c4f-65d7-41c7-a936-5577b1d318d7)
这个应该是cf的警告

**Comment by zc360** [comment]
![屏幕截图 2024-07-28 064319](https://github.com/user-attachments/assets/2adaae0b-0e91-4989-8d99-f4ca277a0097)

**Comment by zc360** [comment]
![4e8c7e10181e26cca1f928b1b82d30d8](https://github.com/user-attachments/assets/c3e1f067-750c-4f72-9d92-3243d5f83552)
这个是Windows defence的警告

**Comment by GamerNoTitle** [comment]
同样收到了邮件，投诉方应该是NetCraft（某知名举报流氓）
![image](https://github.com/user-attachments/assets/b48fbb28-fe62-45de-a4cb-bfa8a4ab0f66)

我的建议是关站，然后先不管着，观望一会

**Comment by GamerNoTitle** [comment]
目前它投诉的是pages.dev这个域名，鬼知道后面会不会投诉我的主域名，所以我就直接删掉了

**Comment by jianjianai** [comment]
我的演示站早就被投诉了，现在还是好好的。等有时间加个密码验证，就扫不到了。

**Comment by sanwecn** [comment]
这个项目现在不能删除pages.dev域名，所以WAF设置的规则拦不住扫描

**Comment by GamerNoTitle** [comment]
> 这个项目现在不能删除pages.dev域名，所以WAF设置的规则拦不住扫描

我问了Discord官方，他们给我的回复是推荐按照下面这个文档配置来重定向到自己的域名

https://developers.cloudflare.com/pages/how-to/redirect-to-custom-domain/

**Comment by sanwecn** [comment]
> > 这个项目现在不能删除pages.dev域名，所以WAF设置的规则拦不住扫描
> 
> 我问了Discord官方，他们给我的回复是推荐按照下面这个文档配置来重定向到自己的域名
> 
> https://developers.cloudflare.com/pages/how-to/redirect-to-custom-domain/

可以添加域名这很简单，但是不能删除默认分配的域名

**Comment by GamerNoTitle** [comment]
> > > 这个项目现在不能删除pages.dev域名，所以WAF设置的规则拦不住扫描
> > 
> > 我问了Discord官方，他们给我的回复是推荐按照下面这个文档配置来重定向到自己的域名
> > 
> > https://developers.cloudflare.com/pages/how-to/redirect-to-custom-domain/
> 
> 可以添加域名这很简单，但是不能删除默认分配的域名

他的意思是，重定向到你自己的域名，相当于pages.dev不可用，你也可以用上你的WAF

![Screenshot_2024-08-01-13-55-33-574_com.discord-edit.jpg](https://github.com/user-attachments/assets/d49133f0-4d40-4ed2-9972-71c78c9fa46c)

**Comment by SokWith** [comment]
这个安全公司是不是毒瘤？
我一个空白站点使用cf自身的服务绑定，居然也报告钓鱼

https://github.com/SokWith/proxy-cf-workers

```
Hello,

Cloudflare received a phishing report regarding: lasa.pages.dev

The information we received was the following:

Reporter: Anonymous

Reported URLs:
https://lasa.pages.dev


Logs or Evidence of Abuse: Appeared in Intel data source


We have forwarded this complaint to your hosting provider.
```
