### ISSUE TITLE
在苹果移动设备上无法使用密码授权登录

### ISSUE THREAD

**Issue by Mokenfly** [jianjianai/microsoft-copilot-porxy#31]
我在苹果移动设备（iPhone&iPad）上不管是用readme里面的演示站还是自建的站点，输入密码点击登录之后都没有反应。如果不设置密码可以使用，但是有Netcraft这种公司一直在扫Workers和Pages，如果扫到微软登录接口就发警告邮件并举报账号。我搭的无密码站点在1天之内就被netcraft扫到了。鉴于苹果移动设备出于苹果的限制，浏览器只能使用WebKit渲染引擎，所以怀疑可能是兼容性问题。在如Android端上用Chrome和Firefox都能成功登录。

**Comment by jianjianai** [comment]
我没有苹果设备，不方便调试，欢迎pr。
