### ISSUE TITLE
账户登录问题：登录后显示same hostname，需要增加跳转连接

### ISSUE THREAD

**Issue by kkou1** [jianjianai/microsoft-copilot-porxy#34]
您好，根据github的文档我已经搭建完成了，但目前情况是无论网络环境或登录方式，均无法登陆微软账户，总显示same hostname。
可能需要增加跳转连接
显示same hostname时地址栏如下：

https://copilot.****.icu/identity/confirm?mkt=ZH-CN&uiflavor=web&id=****&ru=https://copilot.****.icu/login.srf%3fid%3d****%26opid%3d****%26opidt%3d****

**Comment by jianjianai** [comment]
感谢您的 issues。

这个问题很久之前就有人提了，您提供的信息帮助我快速找到问题，非常感谢，因为我的账号登录不会跳转到这个链接无法测试，麻烦您尝试部署最新的  [dev](https://github.com/jianjianai/ms-copilot-play/tree/dev) 分支测试一下，看看是否能正常登录，如果问题解决了麻烦您回复一下，我会将 dev 分支合并到主分支中。

**Comment by kkou1** [comment]
我尝试删除整个github项目与couldflare内的项目，并使用dav内的连接进行重新搭建，同时fork一个dav的分支出来，这种行为算是部署成功dav分支了吗？

目前状态仍是显示same hostname。

**页面连接为**

> https://[copilot.***.top/identity/confirm?mkt=ZH-CN&uiflavor=web&id=***&ru=https://copilot.***.top/login.srf%3fid%3d***%26opidt%3d***]

**github仓库截图如下**
![image](https://github.com/user-attachments/assets/b5bb9571-02d9-4005-898a-357d1d451e8c)

**couldflare版本如下**
![image](https://github.com/user-attachments/assets/495a3905-cc5f-4518-9d20-6fe6215c3e67)


出现上述情况是否因为是我没有切换到dav版本？

或者您方便指导下如何切换为dav版本？

**Comment by qingcimou** [comment]
手动在主分支修改了下，确实可行，本来也是显示same hostname，修改后可以正常登录了

**Comment by jianjianai** [comment]
> 手动在主分支修改了下，确实可行，本来也是显示same hostname，修改后可以正常登录了

非常感谢，稍后我会合并到主分支。

**Comment by jianjianai** [comment]
已解决
