### ISSUE TITLE
cloud flare 的workers pages部署完成后，访问聊天出现：无效城,如果此问题仍然存在,请与站点管理 员联系。

### ISSUE THREAD

**Issue by xingxinag** [jianjianai/microsoft-copilot-porxy#37]
![image](https://github.com/user-attachments/assets/b21558f5-1bca-4124-9409-3abade8e9da9)

**Comment by topsuny** [comment]
I have the same question。。。

**Comment by jiekchenid** [comment]
I have the same question。。。

**Comment by Nitmi** [comment]
the same...

**Comment by SokWith** [comment]
https://github.com/SokWith/mscopilot-proxy/blob/main/README.md

**Comment by jianjianai** [comment]
已解决
