### ISSUE TITLE
访问会概率性进入到新Copilot UI中导致登录跳转URL错误

### ISSUE THREAD

**Issue by WenqiOfficial** [jianjianai/microsoft-copilot-porxy#38]
代理站在新版本部署后会有概率性出现部分设备访问到的是新Copilot UI

在这种情况下登录跳转的URL是微软的根域，就会导致无法跳转回代理站完成登录操作

在我尝试的过程中目前发现手机端浏览器访问的均是旧Copilot UI；
PC使用edge等浏览器有概率性会访问到新Copilot UI，部分设备在访问后刷新会变成旧Copilot UI，但部分设备不行

通过清除缓存和cookies的方法目前都没有解决

新Copilot UI截图：
![image](https://github.com/user-attachments/assets/49c01822-3964-43dc-b20f-c26b8ce29e4c)

**Comment by huxia86465** [comment]
解决了吗我也遇到这个问题了

**Comment by jianjianai** [comment]
已解决

**Comment by huxia86465** [comment]
> 已解决

好的大佬
