### ISSUE TITLE
无法登录，登录界面输入邮箱后，下一步直接弹错误。

### ISSUE THREAD

**Issue by igeekbb** [jianjianai/microsoft-copilot-porxy#39]
如图
![CleanShot 2024-10-14 at 11 37 03@2x](https://github.com/user-attachments/assets/5b98875d-be04-4f84-9d01-73a1bf62d9ca)

**Comment by zwSirius** [comment]
+1

**Comment by dandan7675** [comment]
输入邮箱和密码 无法登陆
提示：Same hostname

**Comment by jianjianai** [comment]
已解决
