### ISSUE TITLE
输入问题后，提示无效域

### ISSUE THREAD

**Issue by jiekchenid** [jianjianai/microsoft-copilot-porxy#40]
输入问题后，提示无效域
输入问题后，提示无效域
输入问题后，提示无效域
输入问题后，提示无效域

**Comment by nikoxp** [comment]
me too.见图片
![11](https://github.com/user-attachments/assets/feaa135c-e42c-4bf2-987a-7f56dec06273)

**Comment by SokWith** [comment]
https://github.com/SokWith/mscopilot-proxy/blob/main/README.md

**Comment by jiekchenid** [comment]
也就是说，无解了。我打开了科学上网了，但还是提示无效域。我部暑完就这样了，没有绑定免费域名，科学上网，还是提示无效域。

**Comment by jianjianai** [comment]
已解决
