### ISSUE TITLE
请教是怎么过验证的？

### ISSUE THREAD

**Issue by SokWith** [jianjianai/microsoft-copilot-porxy#9]
@jianjianai 按照大佬的代码，改了两个pages部署，一个 proxy copilot：  https://mcop.pages.dev  仓库：https://github.com/SokWith/mscopilot-proxy ，一个proxy bing： https://msbing.pages.dev  仓库： https://github.com/SokWith/msbingproxy ;

问题1：copilot无论匿名还是登录，均不跳验证直接使用，原理是什么？
               而 bing 匿名会跳验证并且通不过：
![image](https://github.com/jianjianai/microsoft-copilot-porxy/assets/129967025/07ea808f-6193-4396-8a91-1cf0c73ce935)

问题2： bing 登录后账户无锁时可以使用，但切换到 search后回来就直接跳 sydney.bing.com的聊天服务器，造成会话失败，需要如何更新 rewritebody ？
ps：仿照  https://github.com/Harry-zklcdc/go-proxy-bingai/issues/429#issuecomment-2154429880 采用服务器端rewritebody 是可以 search和copilot间随意跳转的 https://msbi.pages.dev 。

**Comment by SokWith** [comment]
PS：目前Pages部署不费域名，这个项目太耗cf的访问调用次数了，可以使用任意多的小号部署Pages。

**Comment by jianjianai** [comment]
#### 回复1
具体通过验证的原理我也不清楚，这个验证就是个玄学，我小号可以过，大号不知道为什么反正就是过不了。开魔法上网去官网上过了之后就没弹过了。后续打算改用[Harry-zklcdc/go-bingai-pass](https://github.com/Harry-zklcdc/go-bingai-pass)这个项目来通过验证。

#### 回复2
这个问题可能是重新切换回来的时候又和服务器发了一些请求，并且没有替换掉sydney.bing.com，这个可以从网络请求里找到具体的接口，替换一下就能解决。

**Comment by SokWith** [comment]
> #### 回复2
> 这个问题可能是重新切换回来的时候又和服务器发了一些请求，并且没有替换掉sydney.bing.com，这个可以从网络请求里找到具体的接口，替换一下就能解决。

你这个代码，从返回来的前端源代码看，核心js文件都是 r.bing.com/rp/*.js，内容都没有更改过，这一点与[Harry-zklcdc/go-bingai-pass](https://github.com/Harry-zklcdc/go-bingai-pass) 的不同，他的是返回来的都是内容已经替换了的核心CIB.js，那么，rewritebody的更改是由前端注入的代码操作的吗？
我已经添加了对/search请求注入代码了，只实现了create请求的改写，sydney请求失效。但对 /chat请求的注入则是有效的。这两个请求的不同点是，/chat请求是在bing首页的copilot元素点击进入的，而/search转聊天是在 search页面的copilot元素点击进入的

**Comment by jianjianai** [comment]
> 你这个代码，从返回来的前端源代码看，核心js文件都是 r.bing.com/rp/*.js，内容都没有更改过，这一点与[Harry-zklcdc/go-bingai-pass](https://github.com/Harry-zklcdc/go-bingai-pass) 的不同，他的是返回来的都是内容已经替换了的核心CIB.js，那么，rewritebody的更改是由前端注入的代码操作的吗？ 我已经添加了对/search请求注入代码了，只实现了create请求的改写，sydney请求失效。但对 /chat请求的注入则是有效的。这两个请求的不同点是，/chat请求是在bing首页的copilot元素点击进入的，而/search转聊天是在 search页面的copilot元素点击进入的

sydney 请求是 websocket 请求，所以要在前端替换 window.WebSocket 对象才能进行拦截，前端并没有这个操作，而是在后端替换url实现的。

**Comment by SokWith** [comment]
> sydney 请求是 websocket 请求，所以要在前端替换 window.WebSocket 对象才能进行拦截，前端并没有这个操作，而是在后端替换url实现的。

~~我的意思是，无论是/chat还是/search的请求，这个代码返回的核心CIB文件都是官方原版，没有被改写过。从这个官方原版的CIB.js释放启动的wss会话，为什么/chat请求下能够实现sydney的域名改写并正确调用而/search下则没有进行域名改写造成直接调用官方sydney.bing.com服务器从而出错了。即：核心的起动器CIBjs是同一个，为什么请求的源路径不同会发起不同目标路径的调用？/chat是如何做到调用wss时改写sydney域名的~~

不好意思，重新看了一下，/chat请求时是改写了CIB的，而/search请求时是没有改写，问题出在/search页面下点击copilot后的调用没有实现注入rewritebody

**Comment by SokWith** [comment]
原来是两个页面的URL地址写法不一致：
```
/chat:
"rms-answers-CodexBundle-cib-bundle":"https://r.bing.com/rp/2RflyAwwfqjnfw_zP8BVDuk59HE.br.js"

/search:
{'A:rms:answers:CodexBundle:cib-bundle':'https:\/\/r.bing.com\/rp\/2RflyAwwfqjnfw_zP8BVDuk59HE.br.js'},
```

**Comment by SokWith** [comment]
关于认证，也许、大概、可能：
copilot站点没有在cf上针对中国区CDN上做负载均衡，成了漏网之鱼。
